
[top]
text = ""

[down]
text = ""

[files]
include = [
    "desktop.nix", 
    "wallpaper.nix", 
    "configuration.nix", 
    "packages.nix", 
    "home.nix", 
    "*.sh", 
    "Cargo.toml", 
    "*.rs",
    "*.conf"
]
