
[top]
text = ""

[down]
text = ""

[files]
include = [
    "*.nix", 
    # "wallpaper.nix", 
    # "configuration.nix", 
    # "packages.nix", 
    # "home.nix", 
    # "*.sh", 
    # "Cargo.toml", 
    # "*.rs",
    "*.conf"
]
